services:
  binary-buddies-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binary-buddies-web
    network_mode: "host"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
