# -*- coding: utf-8 -*-

from odoo import models, fields, api


class AppAdsTxt(models.Model):
    _name = 'bbweb.app.ads.txt'
    _description = 'App-ads.txt Content Management'
    _order = 'sequence, id'

    name = fields.Char(string='Entry Name', required=True, help='Descriptive name for this entry (e.g., "Google AdMob")')
    sequence = fields.Integer(string='Sequence', default=10, help='Order of appearance in app-ads.txt')
    active = fields.Boolean(string='Active', default=True, help='Only active entries will appear in app-ads.txt')
    
    # App-ads.txt fields (as per IAB standard)
    domain = fields.Char(string='Domain', required=True, help='Ad system domain (e.g., google.com)')
    publisher_id = fields.Char(string='Publisher ID', required=True, help='Your publisher account ID')
    relationship = fields.Selection([
        ('DIRECT', 'Direct'),
        ('RESELLER', 'Reseller')
    ], string='Relationship', required=True, default='DIRECT', help='Account type: DIRECT or RESELLER')
    certification_authority_id = fields.Char(string='Certification Authority ID', help='TAG-ID (e.g., f08c47fec0942fa0 for Google)')
    
    # Additional fields for management
    notes = fields.Text(string='Notes', help='Internal notes about this entry')
    line = fields.Char(string='Generated Line', compute='_compute_line', store=True, 
                       help='The actual line that will appear in app-ads.txt')

    @api.depends('domain', 'publisher_id', 'relationship', 'certification_authority_id')
    def _compute_line(self):
        """Generate the app-ads.txt line from the fields"""
        for record in self:
            parts = [
                record.domain or '',
                record.publisher_id or '',
                record.relationship or 'DIRECT',
            ]
            if record.certification_authority_id:
                parts.append(record.certification_authority_id)
            record.line = ', '.join(parts) if all([record.domain, record.publisher_id]) else ''

    def get_app_ads_txt_content(self):
        """Generate complete app-ads.txt content from all active entries"""
        active_entries = self.search([('active', '=', True)], order='sequence, id')
        
        lines = []
        # Add header comment
        lines.append('# app-ads.txt for Binary Buddies')
        lines.append('# Generated by Odoo CMS')
        lines.append('')
        
        # Add all active entries
        for entry in active_entries:
            if entry.line:
                if entry.notes:
                    # Add comment for notes
                    for note_line in entry.notes.split('\n'):
                        if note_line.strip():
                            lines.append(f'# {note_line.strip()}')
                lines.append(entry.line)
                lines.append('')  # Empty line after each entry
        
        return '\n'.join(lines)

